<?php

/* For large migrations, include the following code: 

**********************

Eloquent::unguard();
DB::connection()->disableQueryLog();

*/

class DatabaseSeeder extends Seeder {

    public function run()
    {
        $this->call('UserTableSeeder');
        //$this->call('InstanceTableSeeder');
        //$this->call('AccountTableSeeder');
        //$this->call('OrganizationTableSeeder');
        $this->command->info('All Tables Seeded!');
    }

}

class UserTableSeeder extends Seeder { 

    public function run()
    {

        User::create(array(
                'username' => 'zeus',
                'password' => Hash::make('password'),
                'email' => 'zeus@olympus.com'
        ));

        User::create(array(
                'username' => 'hera',
                'password' => Hash::make('password'),
                'email' => 'hera@olympus.com'
        ));

        User::create(array(
                'username' => 'pandora',
                'password' => Hash::make('password'),
                'email' => 'pandora@olympus.com'
        ));

        User::create(array(
                'username' => 'prometheus',
                'password' => Hash::make('password'),
                'email' => 'prometheus@olympus.com'
        ));

    }

}


class OrganizationTableSeeder extends Seeder {
 
    public function run() {

       
        Organization::create(    
            array(
                'id' => 1,
                'name' => 'Org.A',
                'description' => 'Your Description Will Go Here',
                'organization' => 1,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

        Organization::create(    
            array(
                'id' => 2,
                'name' => 'Org.B',
                'description' => 'Your Description Will Go Here',
                'organization' => 2,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

        Organization::create(    
            array(
                'id' => 3,
                'name' => 'Org.C',
                'description' => 'Your Description Will Go Here',
                'organization' => 3,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

    }
}



class AccountTableSeeder extends Seeder {
 
    public function run() {

        Account::create(
            array(
                'id' => 1,
                'name' => 'Acct.1.Org.A',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'organization' => 1,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(
            array(
                'id' => 2,
                'name' => 'Acct.2.Org.A',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'organization' => 1,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(    
            array(
                'id' => 3,
                'name' => 'Acct.3.Org.A',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'organization' => 1,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

        Account::create(
            array(
                'id' => 4,
                'name' => 'Acct.4.Org.B',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'organization' => 2,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(
            array(
                'id' => 5,
                'name' => 'Acct.5.Org.B',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'organization' => 2,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(    
            array(
                'id' => 6,
                'name' => 'Acct.6.Org.B',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'access_secret_key_placeholder',
                'organization' => 2,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

                Account::create(
            array(
                'id' => 7,
                'name' => 'Acct.7.Org.C',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'organization' => 3,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(
            array(
                'id' => 8,
                'name' => 'Acct.8.Org.C',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'access_secret_key_placeholder',
                'organization' => 3,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(    
            array(
                'id' => 9,
                'name' => 'Acct.9.Org.C',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'access_secret_key_placeholder',
                'organization' => 3,
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

    }
}




class InstanceTableSeeder extends Seeder {
 
    public function run() {
 
        Instance::create(
            array(
                'id' => 1,
                'name'=>'id-1',
                'kernel' => 'kernel-1',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 1,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 2,
                'name'=>'id-2',
                'kernel' => 'kernel-2',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 1,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id' => 3,
                'name'=>'id-3',
                'kernel' => 'kernel-3',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 1,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id' => 4,
                'name' => 'id-4',
                'kernel' => 'kernel-4',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 2,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id' => 5,
                'name'=>'id-5',
                'kernel' => 'kernel-5',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 2,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id' => 6,
                'name'=>'id-6',
                'kernel' => 'kernel-6',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 2,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=>7,
                'name'=>'id-7',
                'kernel' => 'kernel-7',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 3,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

Instance::create(
            array(
                'id'=> 8,
                'name'=>'id-8',
                'kernel' => 'kernel-8',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 3,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


Instance::create(
            array(
                'id'=> 9,
                'name'=>'id-9',
                'kernel' => 'kernel-9',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 3,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


        Instance::create(
            array(
                'id'=> 10,
                'name'=>'id-10',
                'kernel' => 'kernel-10',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 4,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 11,
                'name'=>'id-11',
                'kernel' => 'kernel-11',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 4,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 12,
                'name'=>'id-12',
                'kernel' => 'kernel-12',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 4,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 13,
                'name'=>'id-13',
                'kernel' => 'kernel-13',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 5,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 14,
                'name'=>'id-14',
                'kernel' => 'kernel-14',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 5,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 15,
                'name'=>'id-15',
                'kernel' => 'kernel-15',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 5,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 16,
                'name'=>'id-16',
                'kernel' => 'kernel-16',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 6,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

Instance::create(
            array(
                'id'=> 17,
                'name'=>'id-17',
                'kernel' => 'kernel-17',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 6,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


Instance::create(
            array(
                'id'=> 18,
                'name'=>'id-18',
                'kernel' => 'kernel-18',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 6,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );




        Instance::create(
            array(
                'id'=> 19,
                'name'=>'id-19',
                'kernel' => 'kernel-19',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 7,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 20,
                'name'=>'id-20',
                'kernel' => 'kernel-20',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 7,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 21,
                'name'=>'id-21',
                'kernel' => 'kernel-21',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 7,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 22,
                'name'=>'id-22',
                'kernel' => 'kernel-22',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 8,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 23,
                'name'=>'id-23',
                'kernel' => 'kernel-23',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 8,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 24,
                'name'=>'id-24',
                'kernel' => 'kernel-24',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 8,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> 25,
                'name'=>'id-25',
                'kernel' => 'kernel-25',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 9,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

Instance::create(
            array(
                'id'=> 26,
                'name'=>'id-26',
                'kernel' => 'kernel-26',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 9,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


        Instance::create(
            array(
                'id' => 27,
                'name' => 'id-27',
                'kernel' => 'kernel-27',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_aws_account' => 9,
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


    }
}