<?php

/* For large migrations, include the following code: 

**********************

Eloquent::unguard();
DB::connection()->disableQueryLog();

*/

class DatabaseSeeder extends Seeder {

    public function run()
    {
        $this->call('UserTableSeeder');
        $this->call('InstanceTableSeeder');
        $this->call('AccountTableSeeder');
        $this->call('OrganizationTableSeeder');
        $this->command->info('All Tables Seeded!');
    }

}

class UserTableSeeder extends Seeder { 

    public function run()
    {

        User::create(array(
                'username' => 'zeus',
                'password' => Hash::make('password'),
                'email' => 'zeus@olympus.com'
        ));

        User::create(array(
                'username' => 'hera',
                'password' => Hash::make('password'),
                'email' => 'hera@olympus.com'
        ));

        User::create(array(
                'username' => 'pandora',
                'password' => Hash::make('password'),
                'email' => 'pandora@olympus.com'
        ));

        User::create(array(
                'username' => 'prometheus',
                'password' => Hash::make('password'),
                'email' => 'prometheus@olympus.com'
        ));

    }

}


class OrganizationTableSeeder extends Seeder {
 
    public function run() {

       
        Organization::create(    
            array(
                'id' => '1',
                'name' => 'Organization#1',
                'description' => 'Your Description Will Go Here',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

        Organization::create(    
            array(
                'id' => '2',
                'name' => 'Organization#2',
                'description' => 'Your Description Will Go Here',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

        Organization::create(    
            array(
                'id' => '3',
                'name' => 'Organization#3',
                'description' => 'Your Description Will Go Here',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

    }
}



class AccountTableSeeder extends Seeder {
 
    public function run() {

        Account::create(
            array(
                'id' => '1',
                'organization_id' => '1',
                'name' => 'A1O1',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(
            array(
                'id' => '2',
                'name' => 'A2O1',
                'organization_id' => '1',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(    
            array(
                'id' => '3',
                'name' => 'A3O1',
                'organization_id' => '1',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

        Account::create(
            array(
                'id' => '4',
                'name' => 'A4O2',
                'organization_id' => '2',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(
            array(
                'id' => '5',
                'name' => 'A5O2',
                'organization_id' => '2',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(    
            array(
                'id' => '6',
                'name' => 'A6O2',
                'organization_id' => '2',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'access_secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

                Account::create(
            array(
                'id' => '7',
                'name' => 'A7O3',
                'organization_id' => '3',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(
            array(
                'id' => '8',
                'name' => 'A8O3',
                'organization_id' => '3',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'access_secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );
        Account::create(    
            array(
                'id' => '9',
                'name' => 'A9O3',
                'organization_id' => '3',
                'access_key' => 'access_key_placeholder',
                'secret_key' => 'access_secret_key_placeholder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

    }
}




class InstanceTableSeeder extends Seeder {
 
    public function run() {
 
        Instance::create(
            array(
                'id' => '1',
                'name'=>'instance-1',
                'organization_id' => '1',
                'account_id' => '1',
                'kernel' => 'kernel-1',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '2',
                'name'=>'instance-2',
                'organization_id' => '1',
                'account_id' => '1',
                'kernel' => 'kernel-2',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id' => '3',
                'name'=>'instance-3',
                'organization_id' => '1',
                'account_id' => '1',
                'kernel' => 'kernel-3',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id' => '4',
                'name' => 'instance-4',
                'organization_id' => '1',
                'account_id' => '2',
                'kernel' => 'kernel-4',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id' => '5',
                'name'=>'instance-5',
                'organization_id' => '1',
                'account_id' => '2',
                'kernel' => 'kernel-5',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id' => '6',
                'name'=>'instance-6',
                'organization_id' => '1',
                'account_id' => '2',
                'kernel' => 'kernel-6',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '7',
                'name'=>'instance-7',
                'organization_id' => '1',
                'account_id' => '3',
                'kernel' => 'kernel-7',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

Instance::create(
            array(
                'id'=> '8',
                'name'=>'instance-8',
                'organization_id' => '1',
                'account_id' => '3',
                'kernel' => 'kernel-8',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


Instance::create(
            array(
                'id'=> '9',
                'name'=>'instance-9',
                'organization_id' => '1',
                'account_id' => '3',
                'kernel' => 'kernel-9',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


        Instance::create(
            array(
                'id'=> '10',
                'name'=>'instance-10',
                'organization_id' => '2',
                'account_id' => '4',
                'kernel' => 'kernel-10',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '11',
                'name'=>'instance-11',
                'organization_id' => '2',
                'account_id' => '4',
                'kernel' => 'kernel-11',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '12',
                'name'=>'instance-12',
                'organization_id' => '2',
                'account_id' => '4',
                'kernel' => 'kernel-12',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '13',
                'name'=>'instance-13',
                'organization_id' => '2',
                'account_id' => '5',
                'kernel' => 'kernel-13',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '14',
                'name'=>'instance-14',
                'organization_id' => '2',
                'account_id' => '5',
                'kernel' => 'kernel-14',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '15',
                'name'=>'instance-15',
                'organization_id' => '2',
                'account_id' => '5',
                'kernel' => 'kernel-15',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '16',
                'name'=>'instance-16',
                'organization_id' => '2',
                'account_id' => '6',
                'kernel' => 'kernel-16',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

Instance::create(
            array(
                'id'=> '17',
                'name'=>'instance-17',
                'organization_id' => '2',
                'account_id' => '6',
                'kernel' => 'kernel-17',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


Instance::create(
            array(
                'id'=> '18',
                'name'=>'instance-18',
                'organization_id' => '2',
                'account_id' => '6',
                'kernel' => 'kernel-18',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );




        Instance::create(
            array(
                'id'=> '19',
                'name'=>'instance-19',
                'organization_id' => '2',
                'account_id' => '7',
                'kernel' => 'kernel-19',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '20',
                'name'=>'instance-20',
                'organization_id' => '2',
                'account_id' => '7',
                'kernel' => 'kernel-20',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '21',
                'name'=>'instance-21',
                'organization_id' => '2',
                'account_id' => '7',
                'kernel' => 'kernel-21',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '22',
                'name'=>'instance-22',
                'organization_id' => '2',
                'account_id' => '8',
                'kernel' => 'kernel-22',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '23',
                'name'=>'instance-23',
                'organization_id' => '2',
                'account_id' => '8',
                'kernel' => 'kernel-23',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '24',
                'name'=>'instance-24',
                'organization_id' => '2',
                'account_id' => '8',
                'kernel' => 'kernel-24',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );



Instance::create(
            array(
                'id'=> '25',
                'name'=>'instance-25',
                'organization_id' => '2',
                'account_id' => '9',
                'kernel' => 'kernel-25',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );

Instance::create(
            array(
                'id'=> '26',
                'name'=>'instance-26',
                'organization_id' => '2',
                'account_id' => '9',
                'kernel' => 'kernel-26',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


        Instance::create(
            array(
                'id' => '27',
                'name' => 'instance-27',
                'organization_id' => '2',
                'account_id' => '9',
                'kernel' => 'kernel-27',
                'instance_profile' => 'normal',
                'root_device_type' => 'root_device_type_holder',
                'private_dns_name' => 'private_dns_name_holder',
                '_state' => 'state_holder',
                'group_name' => 'group_name_holder',
                'public_dns_name' => 'private_dns_name_holder',
                'state_reason' => 'state_reason#',
                'monitored' => 'true',
                'item' => 'item_holder',
                'subnet_id' => 'subnet_id_holder',
                'block_device_mapping' => 'block_device_mapping_holder',
                'platform' => 'platform_holder',
                'events_set' => 'eventsSet_holder',
                'ebs_optimized' => 'ebs_optimized_holder',
                'client_token' => 'client_token_holder',
                '_in_monitoring_element' => '_in_monitoring_element_holder',
                'virtualization_type' => 'virtualization_type_holder',
                'architecture' => 'architecture',
                'ramdisk' => 'ramdisk',
                '_previous_state' => '_previous_state_holder',
                'tags' => 'tags_holder',
                'key_name' => 'key_name_holder',
                'interfaces' => 'interfaces_holder',
                'source_dest_check' => 'sourceDestCheck_holder',
                'image_id' => 'image_id_holder',
                'reason' => 'reason_holder',
                'groups' => 'groups_holder',
                'spot_instance_request_id' => 'spot_instance_request_id_holder',
                'monitoring' => 'monitoring_holder',
                'requester_id' => 'requester_id_holder',
                'ip_address' => 'ip_address_holder',
                'monitoring_state' => 'monitoring_state_holder',
                '_placement' => '_placement_holder',
                'ami_launch_index' => 'ami_launch_index_holder',
                'dns_name' => 'dns_name_holder',
                'region' => 'region_holder',
                'launch_time' => 'launch_time_holder',
                'persistent' => 'persistent_holder',
                'instance_type' => 'instance_type_holder',
                'connection' => 'connection_holder',
                'root_device_name' => 'root_device_name_holder',
                'hypervisor' => 'hypervisor_holder',
                'private_ip_address' => 'private_ip_address_holder',
                'vpc_id' => 'vpc_id_holder',
                'product_codes' => 'product_codes_holder',
                'reliam_created' => new DateTime,
                'reliam_modified' => new DateTime,
                'reliam_status' => 'reliam_status_holder',
                'sys_distribution' => 'sys_distribution_holder',
                'sys_distribution_release' => 'sys_distribution_release_holder',
                'sys_distribution_version' => 'sys_distribution_version_holder',
                'sys_kernel' => 'sys_kernel_holder',
                'sys_machine' => 'sys_machine_holder',
                'updated_at' => new DateTime,
                'created_at' => new DateTime
            )
        );


    }
}